### ISSUE TITLE
0.11.3 release is missing AUTHORS file

### ISSUE THREAD

**Issue by ppisar** [libwbxml/libwbxml#17]
Previous releases delivered AUTHORS file. 0.11.3 does not although the MANIFEST file list it. I think you removed the file by accident.

**Comment by ppisar** [comment]
Actually it causes make install to fail:

```
Install the project...
/usr/bin/cmake -P cmake_install.cmake
-- Install configuration: ""
CMake Error at cmake_install.cmake:44 (file):
  file INSTALL cannot find
  "/home/petr/fedora/libwbxml/libwbxml-0.11.3/AUTHORS".
```

**Comment by bellmich** [comment]
I removed the file because the file THANKS includes the more complete information. The question is, what should I do? I can remove AUTHORS from MANIFEST too but first I have to understand the purpose of the file MANIFEST.

**Comment by bellmich** [comment]
The commit d59ed580e8141fa542b85b0c14de042ce02b20f2 is a quick fix. Still reading to understand MANIFEST fully ...

**Comment by bellmich** [comment]
This issue should be fixed now. Can you please verify it?

**Comment by ppisar** [comment]
On Wed, Apr 08, 2015 at 09:17:10AM -0700, Michael Bell wrote:
> This issue should be fixed now. Can you please verify it?
> 
Yes. Now it installs. Thanks.

-- Petr
