### ISSUE TITLE
check pkg-config module dependency is not documented

### ISSUE THREAD

**Issue by ppisar** [libwbxml/libwbxml#18]
0.11.3 brought a new build-time dependency on check pkg-config module:

```
-- checking for one of the modules 'check'
CMake Error at cmake/modules/FindPkgConfig.cmake:357 (message):
  None of the required 'check' found
Call Stack (most recent call first):
  cmake/modules/FindCheck.cmake:27 (PKG_SEARCH_MODULE)
  test/api/CMakeLists.txt:7 (FIND_PACKAGE)
```

This is not listed in the INSTALL file.

**Comment by bellmich** [comment]
The check stuff is optional. If check is not present then the test directory should be ignored. It looks like a bug in the main CMakeLists.txt

**Comment by bellmich** [comment]
Can you please test the fix?

**Comment by bellmich** [comment]
If the tickets #17 and #18 are fixed then I will release v0.11.4.

**Comment by ppisar** [comment]
On Wed, Apr 08, 2015 at 08:50:42AM -0700, Michael Bell wrote:
> Can you please test the fix?
> 
I confirm, the dependency is optional now and tests pass if the dependency is
available.

-- Petr

**Comment by bellmich** [comment]
Okay, then I start the release of v0.11.4.
