### ISSUE TITLE
CMake Build system does not support to build static library.

### ISSUE THREAD

**Issue by ya1gaurav** [libwbxml/libwbxml#22]
Cmake build system always build shared libwbxml. There is no support for static library building.

**Comment by ya1gaurav** [comment]
https://github.com/libwbxml/libwbxml/pull/27
https://github.com/libwbxml/libwbxml/pull/26
https://github.com/libwbxml/libwbxml/pull/25
https://github.com/libwbxml/libwbxml/pull/24
https://github.com/libwbxml/libwbxml/pull/23

**Comment by bellmich** [comment]
I merged the pull requests and committed an entry to ChangeLog (ae936ced3d6696aa38dd8bd1195c21d18b1af12a).
