### ISSUE TITLE
Stream API

### ISSUE THREAD

**Issue by arcusfelis** [libwbxml/libwbxml#42]
Hi,

Is there stream API like in libexpat? 

> XML_Parse
> int XML_Parse(XML_Parser p, const char *s, int len, int isFinal)
> Parse some more of the document. The string s is a buffer containing part (or perhaps all) of the document. The number of bytes of s that are part of the document is indicated by len. This means that s doesn't have to be null terminated. It also means that if len is larger than the number of bytes in the block of memory that s points at, then a memory fault is likely. The isFinal parameter informs the parser that this is the last piece of the document. Frequently, the last piece is empty (i.e. len is zero.) If a parse error occurred, it returns 0. Otherwise it returns a non-zero value. 

I mean parsing a document piece by piece like in the pseudocode using `parse_more` function:

```c
while (has_more_data())
{
    string data_segment = read_data_from_somewhere();
    parse_more(data_segment);
}
```

**Comment by bellmich** [comment]
No, there is actually no stream API.
