### ISSUE TITLE
8 test cases failing in test suit

### ISSUE THREAD

**Issue by ya1gaurav** [libwbxml/libwbxml#49]
I just used below commands:
mkdir build; cd build; cmake ..;make;make test
I got below errors:
217/224 Test #217: api_private_wbxml_lists ...............***Failed    0.00 sec
        Start 218: api_private_wbxml_buffers
218/224 Test #218: api_private_wbxml_buffers .............***Failed    0.00 sec
        Start 219: api_private_wbxml_base64
219/224 Test #219: api_private_wbxml_base64 ..............***Failed    0.00 sec
        Start 220: api_private_wbxml_charset
220/224 Test #220: api_private_wbxml_charset .............***Failed    0.00 sec
        Start 221: api_private_wbxml_conv
221/224 Test #221: api_private_wbxml_conv ................***Failed    0.00 sec
        Start 222: api_private_wbxml_encoder_internals
222/224 Test #222: api_private_wbxml_encoder_internals ...***Failed    0.00 sec
        Start 223: api_private_wbxml_errors
223/224 Test #223: api_private_wbxml_errors ..............***Failed    0.00 sec
        Start 224: api_private_wbxml_parser_internals
224/224 Test #224: api_private_wbxml_parser_internals ....***Failed    0.00 sec

96% tests passed, 8 tests failed out of 224

Total Test time (real) =  21.67 sec

The following tests FAILED:
        217 - api_private_wbxml_lists (Failed)
        218 - api_private_wbxml_buffers (Failed)
        219 - api_private_wbxml_base64 (Failed)
        220 - api_private_wbxml_charset (Failed)
        221 - api_private_wbxml_conv (Failed)
        222 - api_private_wbxml_encoder_internals (Failed)
        223 - api_private_wbxml_errors (Failed)
        224 - api_private_wbxml_parser_internals (Failed)
Errors while running CTest
make: *** [test] Error 8

**Comment by bellmich** [comment]
Can you please provide the logs from the test run? I made a small change to the buffer API: 524663f3758c2485abd02474a8f4868d5ff05882.

**Comment by ya1gaurav** [comment]
after applying your changes?

**Comment by bellmich** [comment]
When do the failed tests occured? With or without my latest changes? The logs of the failed tests are necessary in every case but it helps to know which version you tested (git commit id).

**Comment by bellmich** [comment]
BTW the latest Travis CI run looks okay: https://travis-ci.org/libwbxml/libwbxml

**Comment by ya1gaurav** [comment]
Hi Bellmich, sorry to bother you. When I run test suite today it works fine for me. Maybe some environment issue. Thanks. Please close this issue.

**Comment by bellmich** [comment]
Thanks for the information. I really like to get very instant feedback. Some false issues are better than one hidden bug. Thanks for your openness.
