### ISSUE TITLE
Ubuntu Maintenance

### ISSUE THREAD

**Issue by nod0n** [libwbxml/libwbxml#50]
Hi

Would you maybe do the maintenance for Ubuntu? The Package hove not been updated for Ubuntu since 0.10.7.

Salutations

**Comment by ya1gaurav** [comment]
You mean there are build errors fro Ubuntu ?

**Comment by nod0n** [comment]
No. It seems like the Ubuntus maintainer does not his job (the package is realy old). So I think Ubuntu should get a newer version. I ask you, if you would become the maintainer for this package for ubuntu.

**Comment by ya1gaurav** [comment]
I can become so, But I don't know how to update a package in Ubuntu.

**Comment by bellmich** [comment]
I don't use Ubuntu and the upstream source repository is not the place to keep an issue open to find a package maintainer. Therefore I close the ticket. Sorry, Michael
