### ISSUE TITLE
The content for element data in code page ResolveRecipients and GAL must be encoded as opaque data.

### ISSUE THREAD

**Issue by tfux** [libwbxml/libwbxml#52]
If I'm not wrong these elements need to be marked with WBXML_TAG_OPTION_BINARY.

**Comment by bellmich** [comment]
Why should these elements be marked as binary? Do you have a reference for this?

**Comment by bellmich** [comment]
Do you have an example? This would be a great help.

**Comment by tfux** [comment]
https://msdn.microsoft.com/en-us/library/gg650842(v=exchg.80).aspx
-> The gal:Data element is an optional child element of the gal:Picture element in Search command responses that contains the binary data of the contact photo
https://msdn.microsoft.com/en-us/library/gg675628(v=exchg.80).aspx
-> The Data element is an optional child element of the Picture element in ResolveRecipients command responses that contains the binary data of the contact photo.

The data element can carry a picture  in a response to a Search (gal) or ResolveRecipients.

**Comment by tfux** [comment]
I'm working on the sogo project which is using libwbxml and want to include the contact picture and the GAL-search response. The problem is, that libwbxml doesn't encode <Data> into a binary array (OPAQUE).

[sample.txt](https://github.com/libwbxml/libwbxml/files/720949/sample.txt)

With the attached modification mobile devices which supporting pictures in GAL-search-responses show them as expected.

[modification.txt](https://github.com/libwbxml/libwbxml/files/720950/modification.txt)

**Comment by bellmich** [comment]
I remember that we had such an issue already in the past with another element. So the patch looks okay. I will commit it. Do you have a sample with a real image? In this case, I would like to add this file as a test case and a documentation.

**Comment by tfux** [comment]
Here a sample with a real image:
[sample-1.txt](https://github.com/libwbxml/libwbxml/files/721766/sample-1.txt)

**Comment by bellmich** [comment]
sample-1.txt included a missing "<". Today I try to create a clean pull request for this issue.

**Comment by bellmich** [comment]
BTW do you have a real name which I should add to the ChangeLog and THANKS file?

**Comment by bellmich** [comment]
I have two additional questions before I can close the issue:

- Do you (or your company) want to be mentioned?
- Do you need an immediate release?

**Comment by tfux** [comment]
For me it's not important to be mentioned.
I think an immediate release would help anybody who is packaging libwbxml with SOGo.
Thanks,
Thomas Führer

**Comment by bellmich** [comment]
I released version 0.11.5. It is available via github and sourceforge. Please check if this release works for you.
