### ISSUE TITLE
attachments->add->content element must be encoded as opaque data.

### ISSUE THREAD

**Issue by tfux** [libwbxml/libwbxml#58]
This element is used when the clients send a request to save a draft email
An example can be found in http://interoperability.blob.core.windows.net/files/MS-ASEMAIL/[MS-ASEMAIL].pdf (4.4 Adding a Draft Email with Attachments)

The element content needs to be encoded as opaque data:

Reference:
https://msdn.microsoft.com/en-us/library/mt563406%28v=exchg.80%29.aspx
[...]
The Content element is a string data type byte array, as specified in [MS-ASDTYPE] section 2.7.1.
[...]

Potential fix:

diff --git a/src/wbxml_tables.c b/src/wbxml_tables.c
index fc678f8..867d0f4 100644
--- a/src/wbxml_tables.c
+++ b/src/wbxml_tables.c
@@ -3088,7 +3088,7 @@ const WBXMLTagEntry sv_airsync_tag_table[] = {
     { "Add",                    0x11, 0x1c }, /* since 16.0 */
     { "Delete",                 0x11, 0x1d }, /* since 16.0 */
     { "ClientId",               0x11, 0x1e }, /* since 16.0 */
-    { "Content",                0x11, 0x1f }, /* since 16.0 */
+    { "Content",                0x11, 0x1f, WBXML_TAG_OPTION_BINARY }, /* since 16.0 */
     { "Location",               0x11, 0x20 }, /* since 16.0 */
     { "Annotation",             0x11, 0x21 }, /* since 16.0 */
     { "Street",                 0x11, 0x22 }, /* since 16.0 */

**Comment by bellmich** [comment]
Sorry for the delay, I am waiting for DSL since four months at my new flat. Do you need an immediate release?

**Comment by tfux** [comment]
An immediate release would appreciated. Thanks!

**Comment by bellmich** [comment]
I start the release process now.

**Comment by bellmich** [comment]
The new release is available.
