### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by TBK** [libwbxml/libwbxml#68]
Would it be possible to make a new release?

**Comment by bellmich** [comment]
Yes, of course this is possible. I will start the preparations. This could need 2 or 3 days.

**Comment by TBK** [comment]
Super :+1:

**Comment by bellmich** [comment]
Issue #69 is the pull request for the new release.

**Comment by bellmich** [comment]
I just discovered a missing contributor in the file THANKS. So another pull request ... #70.

**Comment by bellmich** [comment]
The release is complete. The tag is libwbxml-0.11.7.
