### ISSUE TITLE
Error 4061 when compiling on win32

### ISSUE THREAD

**Issue by mukunda-** [libwbxml/libwbxml#75]
For anyone compiling this in the modern-day, this causes a handful of compiler errors.

https://github.com/libwbxml/libwbxml/blob/master/src/wbxml_internals.h#L129 

![image](https://user-images.githubusercontent.com/7541831/119208999-149c0100-ba6a-11eb-9a86-77df7e67fdbb.png)

**Comment by bellmich** [comment]
I never tried to compile the library on win32. If this gives compiler errors, I need to know if the pragma itself is outdated or some code causes this.

**Comment by bellmich** [comment]
P.S. I have no windows machine to test this.

**Comment by bellmich** [comment]
My missing knowledge around Windows is the reason why I never tried to configure a GitHub runner for Windows. 🤷‍♂️

**Comment by mukunda-** [comment]
I'm not too sure either @bellmich. I doubt it matters very much today; [my use case for libwbxml was very niche](https://blog.mukunda.com/cat/2021/activesync-hell.txt), just a program to debug some ActiveSync problems for a product, and I work on Windows. I just wanted to warn other people who might try to compile on Windows.

**Comment by bellmich** [comment]
Well, but you succeeded in compiling it according to the blog. 😉 Do you still know which pragmas did you remove? I could remove them from the header file in case somebody needs the library on a windows system again. Was it just about the one referenced pragma?

**Comment by mukunda-** [comment]
I believe it was that one highlighted pragma only (it's been a while though). I don't know what side effects might be introduced from removing it, but it worked for me.

**Comment by bellmich** [comment]
I will provide a patch tomorrow morning (CEST) to fix this.

**Comment by bellmich** [comment]
I merged my pull request #94 to fix this issue. Of course this doesn't fix the problem of the missing GitHub runners for windows-latest but at minimum the library should be usable.

**Comment by mukunda-** [comment]
Cool. I'm not using the lib since that debugging incident 3 years ago, but this lib was a lifesaver for translating the old binary protocols. Thanks for your work on it.

**Comment by bellmich** [comment]
Thank you! 🤗 Potentially, I will find an example on how to configure the build process for windows-latest but for now I close the issue.
