### ISSUE TITLE
Vulnerable Expat 1.95.6 bundled at macosx/expat/

### ISSUE THREAD

**Issue by hartwork** [libwbxml/libwbxml#77]
Hi libwbxml,

it came to my attention that you have a bundle of vulnerable Expat 1.95.6 of 2003 at [`macosx/expat/`](https://github.com/libwbxml/libwbxml/tree/master/macosx/expat). If that's used for anything, please upgrade to latest 2.4.6 with many security fixes.

Thanks and best, Sebastian

**Comment by bellmich** [comment]
I was not aware that there is a complete copy of Expat somewhere in the code. I will try to remove it from the code and see if the tests are still running.

**Comment by hartwork** [comment]
Hi @bellmich that would be great. From another quick look, that copy may indeed be unused.

PS: Any help with https://github.com/libwbxml/libwbxml/issues/76#issuecomment-1049850370 would also rock, if you have a minute.

**Comment by hartwork** [comment]
@bellmich update on that: Seems like @SlavekB figured things out already (PR #78)

**Comment by bellmich** [comment]
I merged the pull request after the automated tests succeeded which should fix this issue.
