### ISSUE TITLE
README says releases available at SourceForge, but that's only through 0.11.6

### ISSUE THREAD

**Issue by nieder** [libwbxml/libwbxml#80]
The SF site only has releases through 0.11.6.

**Comment by bellmich** [comment]
Sorry, my fault. I was not sure if it is enough to continue on GitHub and how to cleanly do it. You are completely right that the actual situation is a mess.

**Comment by bellmich** [comment]
The plan to fix this would be:

- statement on SourceForge
- correct README
- fresh release
- upload the 0.11.7 to SourceForge as the README  requires this

@nieder, do you think this is enough?

**Comment by nieder** [comment]
That's probably fine. I know from experience that it's easy to forget a secondary release site. I was tracking SF for releases and I think I only clicked on the github pointer by chance, so it's not necessarily clear that development is now here.
If you do want to stay just on github (code, issues, releases), then editing the SF README to point here and the github README to only say historical releases are at SF should be enough.

**Comment by bellmich** [comment]
README is fixed. Next step is a fresh release.

**Comment by bellmich** [comment]
A new release with a fixed README is available. Next step is to take care about SourceForge. This will not happen before tomorrow.

**Comment by nieder** [comment]
Thank you!

**Comment by bellmich** [comment]
@nieder, sorry for re-opening the issue but I am not done. The situation is still inconsistent especially on SourceForge. I finished the internal work but not the real problem which you observed and thankfully reported.

**Comment by bellmich** [comment]
I took care about SourceForge. There is a new statement and a notice that the project was migrated.
