### ISSUE TITLE
Transitive dependencies in libwbxml2-config.cmake?

### ISSUE THREAD

**Issue by ppisar** [libwbxml/libwbxml#96]
cmake/libwbxml2-config.cmake.in now contains:

~~~~
FIND_PACKAGE( Expat REQUIRED )
FIND_PACKAGE( PkgConfig )
IF(PKGCONFIG_FOUND)
    PKG_SEARCH_MODULE( CHECK check )
ENDIF(PKGCONFIG_FOUND)
FIND_PACKAGE( Iconv )
~~~~

Is the really necessary? It looks like it adds imposes libwbxml's build-time dependencies to libwbxml applications. Shouldn't the whole block be removed?

One reason for `FIND_PACKAGE( Expat REQUIRED )` could be linking to a static libwbxml library. But it looks strange as EXPAT_LIBRARIES is nowhere propagated to LIBWBXML2_LIBRARIES. I'm don't know much about CMake and its support for static libraries. I believe that for dynamic libarires, which I'm interested in, the whole block is useless.

**Comment by bellmich** [comment]
First of all, thanks for looking into these details and second, I'm not a cmake expert too. 🤷‍♂️ I looked into the old cmake find module [FindLibWbxml2.cmake](https://github.com/libwbxml/libwbxml/commit/667fca2609aded2fe61d1d58edc3dc5a8fb200e0#diff-34808a1639a45e4db63f74b7dac27ade5f5a22a5d7a96858554e8dc0b3e6558a). There, I discovered the reference to expat and remembered that some folks needed to link wbxml statically.

Nevertheless, if it is possible to make the config file even smaller, I'm all in. As cmake is only for building and not binary dependency management, I would give it a try and we just remove the block. If later someone has problems with statical linking, I would automatically analyze the issue with right expert for this usecase, so no guessing. Today, I don't know a single user of the old find module.

**Comment by bellmich** [comment]
I merged the according pull request #97. Should I do a fresh release now as it is usually easier to maintain packages without extra patches?

**Comment by ppisar** [comment]
I don't mind. I found the dependency is not a new problem for my packaging in Fedora because there is already that dependency for a pkgconfig file.

**Comment by bellmich** [comment]
Okay, I close this issue for now and if there are no issues over the next week or so, I will do the next release to achieve a clean release state. Thanks a lot for all your efforts!

**Comment by jm809** [comment]
@bellmich
